version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    ports:
    - 3000:3000
    environment:
    - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    links:
    - db
    volumes:
    - ./grafana-storage:/var/lib/grafana
  server:
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    container_name: server
    ports: 
      - "5000:5000"
volumes:
  dbdata:
  grafana-storage: